language: rust

rust:
    - stable
    - nightly

env:
    - BUILD=test
    - BUILD=codegen

install:
    - rvm use 2
    - make install-$BUILD

script:
    - make TMP_DIR=$PWD/tmp $BUILD
    - git diff --exit-code
