language: rust

rust:
    - stable
    - nightly

env:
    - BUILD=test
    - BUILD=clippy
    - BUILD=codegen

matrix:
    exclude:
        - env: BUILD=clippy  # clippy requires nightly
          rust: stable

install:
    - rvm use 2
    - make install-$BUILD

script:
    - make TMP_DIR=$PWD/tmp $BUILD
    - git diff --exit-code
