sudo: false
language: rust

rust:
    - stable
    - beta

env:
    - BUILD=test
    - BUILD=codegen

install:
      # remotestorage testsuite only runs on rubby 2
    - rvm use 2
    - make install-$BUILD

script:
    - make TMP_DIR=$PWD/tmp $BUILD
    - git diff --exit-code

cache:
    directories:
        - $HOME/.cargo
        - target
