[package]
name = "mysteryshack"
version = "0.1.0"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["remotestorage"]
readme = "README.md"

[lib]
name = "mysteryshack"
path = "src/mysteryshack/lib.rs"

[[bin]]
name = "mysteryshack"
test = false
doc = false

[dependencies]
rustc-serialize = "*"
iron = "0.3"
router = "*"
hyper = "*"
toml = "0.2"
unicase = "*"
atomicwrites = "*"
url = "*"
clap = "2"
rand = "*"
persistent = "*"
urlencoded = "*"
handlebars-iron = "*"
handlebars = "*"
regex = "*"
iron-login = "0.4"
quick-error = "1"
mount = "0.1"
time = "0.1"
filetime = "0.1"
chrono = "0.2"
nix = "0.5"
clippy = {git = "https://github.com/Manishearth/rust-clippy", version = "*", optional = true}
webicon = "0.2"
rust_sodium = "0.1"
iron-error-router = "0.1"
please-clap = "*"
termion = "*"

[dev-dependencies]
tempdir = "*"

[features]
default = []
