[package]
name = "mysteryshack"
version = "0.1.0"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["remotestorage"]
readme = "README.md"

[lib]
name = "mysteryshack"
path = "src/mysteryshack/lib.rs"

[[bin]]
name = "mysteryshack"
test = false
doc = false

[dependencies]
rustc-serialize = "*"
iron = "*"
router = "*"
hyper = "*"
toml = "*"
unicase = "*"
atomicwrites = "*"
url = "0.2"  # blocked by https://github.com/servo/rust-url/pull/138
clap = "*"
rust-crypto = "*"
rand = "*"
persistent = "*"
urlencoded = "*"
handlebars-iron = "*"
regex = "*"
iron-login = "*"
quick-error = "*"
staticfile = "*"
mount = "*"
time = "*"
filetime = "*"
chrono = "*"
