[package]
name = "mysteryshack"
version = "0.1.0"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["remotestorage"]
readme = "README.md"

[lib]
name = "mysteryshack"
path = "src/mysteryshack/lib.rs"

[[bin]]
name = "mysteryshack"
test = false
doc = false

[dependencies]
rustc-serialize = "0.3"
iron = "0.3"
router = "0.1"
hyper = "0.8"
toml = "0.2"
unicase = "1"
atomicwrites = "0.0"
url = "0.5"
clap = "2"
rand = "0.3"
persistent = "0.1"
urlencoded = "0.3"
handlebars-iron = "=0.15.1"
handlebars = "=0.16.0"
regex = "0.1"
iron-login = "0.4"
quick-error = "1"
mount = "0.1"
time = "0.1"
filetime = "0.1"
chrono = "0.2"
nix = "0.5"
clippy = {git = "https://github.com/Manishearth/rust-clippy", version = "*", optional = true}
webicon = "0.2"
rust_sodium = "0.1"
iron-error-router = "0.1"
please-clap = "0.1"
termion = "1"

[dev-dependencies]
tempdir = "*"

[features]
default = []
