[package]
name = "mysteryshack"
version = "0.1.0"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["remotestorage"]
readme = "README.md"

[lib]
name = "mysteryshack"
path = "src/mysteryshack/lib.rs"

[[bin]]
name = "mysteryshack"
test = false
doc = false

[dependencies]
rustc-serialize = "*"
iron = "*"
router = "*"
hyper = "*"
toml = "*"
unicase = "*"
atomicwrites = "*"
url = "*"
clap = "*"
rust-crypto = "*"
rand = "*"
persistent = "*"
urlencoded = "*"
handlebars-iron = "*"
handlebars = "0.12"
regex = "*"
iron-login = "*"
quick-error = "*"
staticfile = {version = "*", features = ["cache"]}
mount = "*"
time = "*"
filetime = "*"
chrono = "*"
nix = "*"
itertools = "*"
jsonwebtoken = "*"
uuid = "*"
clippy = {git = "https://github.com/Manishearth/rust-clippy", version = "*", optional = true}
webicon = {git = "https://github.com/untitaker/rust-webicon", version = "*"}

[dev-dependencies]
tempdir = "*"

[features]
default = []
